config/routes.rb
Rails.application.routes.draw do
  root 'posts#newest'
  get '/post/:id' => 'posts#show', as: :post
  get '/about/' => 'about#show', as: :about
  get '/search/' => 'search#show', as: :search
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController

  def show
    @latest = Post.all.sort_by { |post| post.created_at }
    @oldest = Post.all.sort_by { |post| post.created_at }.first
    @title = "About"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController


  def index
    @posts = Post.all.sort_by { |post| post.created_at }.reverse
    if params[:id]
      @posts = Post.find(params[:id]).order('created_at DESC')
    else
      @posts = Post.all.order('created_at DESC')
    end
  end

  def newest
    @ordered = Post.all.sort_by { |post| post.created_at }.reverse
    @newest = (Post.all.sort_by { |post| post.created_at }.reverse).first
    @post = Post.find(params[:id])
    @title = @newest.title
  end

  def show
    @ordered = Post.all.sort_by { |post| post.created_at }.reverse
    @post = Post.find(params[:id])
    @title = @post.title
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def posts
    @posts = Post.all
    if params[:search]
      @posts = Post.search(params[:search]).order("created_at DESC")
    else
      @posts = Post.all.order('created_at DESC')
    end
  end

  def show
    @latest = Post.all.sort_by { |post| post.created_at }
    @oldest = Post.all.sort_by { |post| post.created_at }.first
    @title = "About"
  end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%= @title %> </title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="page-heading">
        <div class="jumbotron text-center">
            <nav class="navbar navbar-transparent">
                <div class="container-fluid">
                    <div class="navbar-header"><a class="navbar-brand" href="#"><span class="glyphicon glyphicon-header" aria-hidden="true"></span>HODOR &amp; HODOR HDR. BLOG</a></div>
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav navbar-right">
                            <li><a href="#">HODOR</a></li>
                            <li class="form-group navbar-form has-feedback has-feedback-right">
                              <%= form_tag(search_path, :method => "get", id: "search-form") do %>
                              <%= text_field_tag :search, params[:search], placeholder: "Hodor" %>
                              <%= submit_tag 'Hodor' %>
                              <% end %>
                        </ul>
                    </div>
                </div>
            </nav>
            <h1>HODOR &amp; HODOR HDR.</h1>
            <h4>Hodor Hodor Hodor-hodor. Hodor, Winter 2016.</h4>
        </div>
    </header>
    <main>
        <div class="container-fluid">
            <div class="col-xs-10 col-xs-offset-1">
                <div class="container col-xs-8">
                  <%= yield :post %>
                  <%= yield :about %>
                  <%= yield :results %>
                </div>
                <div class="col-xs-4 container sidebar">
                    <div class="profile">
                      <%= yield :author %>
                    </div>
                    <div class="adspace hovereffect container-fluid"><%= image_tag 'ads/ad', class: 'img-responsive', alt: "adspace" %>
                        <div class="overlay adlink">
                            <a class="" href="#"></a>
                        </div>
                    </div>
                    <div class="ad-info"><a href="#">About this hodor.</a></div>
                    <h3>Hodor hodor hodor.</h3>
                    <div>
                        <h5>HODOR hodor, hodor hodor; hodor hodor hodor! Hodor, hodor - hodor?! Hodor hodor, hodor. Hodor HODOR hodor, hodor hodor, hodor, hodor hodor. Hodor hodor - hodor hodor HODOR hodor, hodor hodor - hodor hodor!</h5>
                    </div>
                </div>
            </div>
        </div>
        <hr>
        <section class="container-fluid" id="box-strip">
            <section class="text-center">
                <h1>Hodor Hodor, HODOR</h1>
            </section>
            <section>
              <%= yield :bar %>
            </section>
        </section>
    </main>
    <footer class="navbar">
        <div class="container-fluid navbar-footer">
            <div class="nav navbar-form navbar-left">
                <h5>Hodor hodor hodor, 2016. Hodor-hodor, Hodor.</h5>
            </div>
            <nav>
                <ul class="nav navbar-nav navbar-right">
                    <li><%= link_to 'Latest post', root_path %></li>
                    <li><%= link_to 'About this page', about_path %></li>
                    <li><a href="#">HODOR</a></li>
                    <li><a href="#">Hodor Hodor</a></li>
                </ul>
            </nav>
        </div>
    </footer>
</html>

app/views/layouts/posts.html.erb
<%= render partial: 'post' %>